import type { PortalState, Resource, ResourceCategory } from "./portal-types";

const categories: ResourceCategory[] = [
  { id: "cat-company", name: "Company Policies", icon: "BookOpen", order: 1 },
  { id: "cat-safety", name: "Safety & Compliance", icon: "ShieldCheck", order: 2 },
  { id: "cat-field-ops", name: "Field Operations", icon: "Compass", order: 3 },
  { id: "cat-equipment", name: "Equipment & Products", icon: "Wrench", order: 4 },
  { id: "cat-treatment", name: "Treatment Protocols", icon: "FlaskConical", order: 5 },
  { id: "cat-sales", name: "Sales Tools", icon: "TrendingUp", order: 6 },
  { id: "cat-ops-admin", name: "Operations", icon: "Settings", order: 7 },
];

const resources: Resource[] = [
  // ── GLOBAL — Company Policies ──
  {
    id: "res-handbook",
    title: "Employee Handbook 2026",
    description:
      "Complete handbook: policies, benefits, time-off procedures, code of conduct, and everything you need to know as a team member.",
    type: "pdf",
    url: "https://docs.google.com/document/d/1vJg5gG58pcnGE6D3M_TcT65BRab6Urtx/edit?usp=sharing&ouid=117890417828874472382&rtpof=true&sd=true",
    categoryId: "cat-company",
    tags: ["handbook", "policies", "hr"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "~4 MB",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-org-chart",
    title: "Company Org Chart",
    description:
      "Organizational structure and reporting chain.",
    type: "pdf",
    url: "",
    categoryId: "cat-company",
    tags: ["org-chart", "structure"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "~500 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-brand-guidelines",
    title: "Brand Guidelines",
    description:
      "Logo usage, colors, uniform standards, and vehicle branding.",
    type: "pdf",
    url: "",
    categoryId: "cat-company",
    tags: ["brand", "guidelines", "logo"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~2 MB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },

  // ── GLOBAL — Safety & Compliance ──
  {
    id: "res-ppe-checklist",
    title: "PPE Checklist",
    description:
      "Required personal protective equipment by service type.",
    type: "pdf",
    url: "",
    categoryId: "cat-safety",
    tags: ["ppe", "safety", "checklist"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-emergency-card",
    title: "Emergency Contact Card",
    description:
      "Printable card: poison control, hospital, and manager contacts.",
    type: "pdf",
    url: "",
    categoryId: "cat-safety",
    tags: ["emergency", "contacts", "safety"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "~200 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-sds-binder",
    title: "Safety Data Sheet Binder",
    description:
      "Complete SDS for every product in the Hydra lineup. Required on every vehicle.",
    type: "pdf",
    url: "",
    categoryId: "cat-safety",
    tags: ["sds", "safety", "compliance"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "~12 MB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-az-regulations",
    title: "Arizona Pest Control Regulations",
    description:
      "AZ Dept of Agriculture Pest Management Division regulations. All technicians must be familiar with state licensing and compliance requirements.",
    type: "link",
    url: "https://agriculture.az.gov/pestspest-control/pest-management-division",
    categoryId: "cat-safety",
    tags: ["regulations", "compliance", "arizona"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: false,
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },

  // ── OPS — Field Operations ──
  {
    id: "res-service-checklist",
    title: "Service Visit Checklist",
    description:
      "Standard checklist for every residential and commercial visit.",
    type: "pdf",
    url: "",
    categoryId: "cat-field-ops",
    tags: ["checklist", "service", "field"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-pest-field-card",
    title: "Pest Identification Field Card",
    description:
      "Printable quick-reference: top 20 AZ pests with photos and treatment approach.",
    type: "pdf",
    url: "",
    categoryId: "cat-field-ops",
    tags: ["field-card", "identification", "reference"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~2 MB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-seasonal-calendar",
    title: "Seasonal Pest Calendar",
    description:
      "Month-by-month pest activity chart for all 3 service regions.",
    type: "pdf",
    url: "",
    categoryId: "cat-field-ops",
    tags: ["seasonal", "calendar", "pests"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~500 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },

  // ── OPS — Equipment & Products ──
  {
    id: "res-mixing-chart",
    title: "Product Mixing Chart",
    description:
      "Mixing ratios for every product in the Hydra lineup.",
    type: "pdf",
    url: "",
    categoryId: "cat-equipment",
    tags: ["mixing", "products", "ratios"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~400 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-equipment-checklist",
    title: "Daily Equipment Checklist",
    description:
      "Pre-route check for sprayers, backpacks, vehicle rig, and tools.",
    type: "pdf",
    url: "",
    categoryId: "cat-equipment",
    tags: ["equipment", "checklist", "daily"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-vehicle-inspection",
    title: "Vehicle Inspection Form",
    description:
      "Weekly vehicle condition and inventory form.",
    type: "pdf",
    url: "",
    categoryId: "cat-equipment",
    tags: ["vehicle", "inspection", "form"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },

  // ── OPS — Treatment Protocols ──
  {
    id: "res-hydra-guard-sop",
    title: "Hydra-Guard Barrier Application SOP",
    description:
      "Step-by-step barrier application: spray patterns, mixing, and coverage.",
    type: "pdf",
    url: "",
    categoryId: "cat-treatment",
    tags: ["hydra-guard", "barrier", "sop"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~1 MB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-icap-label",
    title: "iCap Product Label & Rates",
    description:
      "Product label with application rate chart.",
    type: "pdf",
    url: "",
    categoryId: "cat-treatment",
    tags: ["icap", "product", "rates"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~500 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-pretreat-protocol",
    title: "Termite Pre-Construction Protocol",
    description:
      "Pre-treatment procedure: soil prep, chemical zones, and documentation.",
    type: "pdf",
    url: "",
    categoryId: "cat-treatment",
    tags: ["termite", "pre-construction", "protocol"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~1 MB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-wdiir-form",
    title: "WDIIR Form Template",
    description:
      "Wood Destroying Insect Inspection Report template.",
    type: "pdf",
    url: "",
    categoryId: "cat-treatment",
    tags: ["wdiir", "termite", "inspection"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~400 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },

  // ── SALES — Sales Tools ──
  {
    id: "res-pricing-guide",
    title: "Service Pricing & Packages Guide",
    description:
      "Current pricing, bundles, and seasonal promotions. Updated monthly.",
    type: "pdf",
    url: "",
    categoryId: "cat-sales",
    tags: ["pricing", "sales", "packages"],
    assignedDepartments: ["dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~2 MB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-upsell-guide",
    title: "Upsell Opportunity Guide",
    description:
      "How to spot and present add-on services during visits.",
    type: "pdf",
    url: "",
    categoryId: "cat-sales",
    tags: ["upsell", "sales", "opportunities"],
    assignedDepartments: ["dept-ops", "dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~500 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-referral-overview",
    title: "Referral Program Overview",
    description:
      "Referral program details, cards, tracking, and bonus eligibility.",
    type: "pdf",
    url: "",
    categoryId: "cat-sales",
    tags: ["referrals", "program", "bonus"],
    assignedDepartments: ["dept-ops", "dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~400 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-customer-scripts",
    title: "Customer Communication Scripts",
    description:
      "Greeting, walkthrough, objection handling, and close scripts.",
    type: "pdf",
    url: "",
    categoryId: "cat-sales",
    tags: ["scripts", "customer", "communication"],
    assignedDepartments: ["dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-complaint-flowchart",
    title: "Complaint Resolution Flowchart",
    description:
      "Step-by-step guide to handling customer concerns.",
    type: "pdf",
    url: "",
    categoryId: "cat-sales",
    tags: ["complaints", "resolution", "customer-service"],
    assignedDepartments: ["dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },

  // ── ADMIN — Operations ──
  {
    id: "res-route-optimization",
    title: "Route Optimization Best Practices",
    description:
      "Tips for planning efficient daily routes and minimizing windshield time.",
    type: "document",
    url: "",
    categoryId: "cat-ops-admin",
    tags: ["routes", "efficiency", "operations"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~500 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-warranty-template",
    title: "Warranty Documentation Template",
    description:
      "Template for treatment warranty paperwork.",
    type: "pdf",
    url: "",
    categoryId: "cat-ops-admin",
    tags: ["warranty", "documentation", "template"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "res-builder-checklist",
    title: "Builder Coordination Checklist",
    description:
      "Pre-con treatment coordination with GCs and builders.",
    type: "pdf",
    url: "",
    categoryId: "cat-ops-admin",
    tags: ["builder", "coordination", "pre-construction"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "~300 KB",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
];

export function getInitialState(): PortalState {
  return {
    employees: [
      {
        id: "emp-001",
        name: "Admin",
        email: "admin@hydrapest.com",
        pin: "0000",
        role: "admin",
        departmentId: "dept-ops",
        positionId: "pos-gm",
        locationId: "loc-gila",
        status: "active",
        createdAt: "2026-01-01T00:00:00Z",
      },
    ],
    departments: [
      { id: "dept-ops", name: "Operations", description: "Field operations and service delivery", color: "hydra-teal" },
      { id: "dept-sales", name: "Sales", description: "Sales and customer acquisition", color: "hydra-cyan" },
      { id: "dept-admin", name: "Administration", description: "Office and administrative support", color: "hydra-gray" },
    ],
    positions: [
      { id: "pos-gm", name: "General Manager", departmentId: "dept-ops" },
      { id: "pos-tech", name: "Technician", departmentId: "dept-ops" },
      { id: "pos-sales", name: "Sales Rep", departmentId: "dept-sales" },
    ],
    locations: [
      { id: "loc-gila", region: "Gila Valley", address: "2158 N Reay Ln Suite 1, Thatcher, AZ 85552", phone: "833-493-7229" },
      { id: "loc-white", region: "White Mountains", address: "1080 N 16th St Suite 300, Show Low, AZ 85901", phone: "833-493-7229" },
      { id: "loc-sierra", region: "Sierra Vista", address: "4148 Industry Dr Suite 1111, Sierra Vista, AZ 85650", phone: "833-493-7229" },
    ],
    resources,
    categories,
    completions: [],
  };
}

export function getAllResourceIds(): string[] {
  return resources.map((r) => r.id);
}
