import type { PortalState, Resource, ResourceCategory } from "./portal-types";

const categories: ResourceCategory[] = [
  { id: "cat-onboarding", name: "Onboarding", icon: "Shield", order: 1 },
  { id: "cat-pest-id", name: "Pest Identification", icon: "Bug", order: 2 },
  { id: "cat-treatment", name: "Treatment Procedures", icon: "FlaskConical", order: 3 },
  { id: "cat-equipment", name: "Equipment & Products", icon: "Wrench", order: 4 },
  { id: "cat-safety", name: "Safety & Compliance", icon: "ShieldCheck", order: 5 },
  { id: "cat-sales", name: "Sales & Growth", icon: "TrendingUp", order: 6 },
  { id: "cat-company", name: "Company Policies", icon: "BookOpen", order: 7 },
];

const resources: Resource[] = [
  {
    id: "res-welcome",
    title: "Welcome to Hydra Pest Control",
    description:
      "Get to know Hydra Pest Control — our mission, values, and what makes us different. Covers company history, organizational structure, and the standards we hold ourselves to.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-onboarding",
    tags: ["onboarding", "culture"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    duration: "15 min",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "res-safety-ppe",
    title: "Safety Protocols & PPE Requirements",
    description:
      "Your safety is non-negotiable. Learn the required personal protective equipment for every job type, proper chemical handling procedures, emergency protocols, and OSHA compliance.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-onboarding",
    tags: ["safety", "ppe", "osha"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    duration: "20 min",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "res-customer-service",
    title: "Customer Service Standards",
    description:
      "Every interaction is a chance to build trust. Learn Hydra's communication guidelines, how to handle complaints, and the small touches that turn customers into advocates.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-onboarding",
    tags: ["customer-service", "communication"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    duration: "12 min",
    createdAt: "2026-03-02T00:00:00Z",
    updatedAt: "2026-03-02T00:00:00Z",
  },
  {
    id: "res-employee-handbook",
    title: "Employee Handbook 2026",
    description:
      "The complete Hydra Pest Control employee handbook covering policies, benefits, time-off procedures, code of conduct, and everything you need to know as a team member.",
    type: "pdf",
    url: "#",
    categoryId: "cat-company",
    tags: ["handbook", "policies", "hr"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "4.2 MB",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "res-scorpions",
    title: "Arizona Scorpions: Identification & Treatment",
    description:
      "Arizona is home to over 40 scorpion species, including the bark scorpion. Learn to identify common species, understand behavior patterns, and apply correct treatment protocols.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-pest-id",
    tags: ["scorpions", "identification"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "18 min",
    createdAt: "2026-03-03T00:00:00Z",
    updatedAt: "2026-03-03T00:00:00Z",
  },
  {
    id: "res-termites",
    title: "Termite Identification & Inspection Procedures",
    description:
      "Master the differences between subterranean and drywood termites, learn to spot evidence of infestation, and understand the WDIIR process.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-pest-id",
    tags: ["termites", "inspection", "wdiir"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "25 min",
    createdAt: "2026-03-04T00:00:00Z",
    updatedAt: "2026-03-04T00:00:00Z",
  },
  {
    id: "res-common-pests",
    title: "Common Arizona Pests: Field Guide",
    description:
      "Quick-reference training on the most common pests you'll encounter — from black widows and brown recluses to roof rats, pigeons, bed bugs, and kissing bugs.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-pest-id",
    tags: ["field-guide", "identification"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "22 min",
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "res-hydra-guard",
    title: "Hydra-Guard Barrier Application",
    description:
      "The Hydra-Guard barrier is our signature perimeter treatment. Learn the step-by-step application process, proper spray patterns, product mixing ratios, and customer communication.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-treatment",
    tags: ["hydra-guard", "barrier", "application"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "16 min",
    createdAt: "2026-03-06T00:00:00Z",
    updatedAt: "2026-03-06T00:00:00Z",
  },
  {
    id: "res-icap",
    title: "iCap Technology: Proper Application",
    description:
      "iCap microencapsulated formulation requires specific handling and application techniques. Learn proper storage, mixing, application methods, and the science behind microcap technology.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-treatment",
    tags: ["icap", "microencapsulation"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "14 min",
    createdAt: "2026-03-07T00:00:00Z",
    updatedAt: "2026-03-07T00:00:00Z",
  },
  {
    id: "res-termite-precon",
    title: "Termite Pre-Construction Treatment",
    description:
      "Pre-construction termite treatment is a critical revenue stream. Learn the complete protocol including soil preparation, chemical application zones, and builder coordination.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-treatment",
    tags: ["termite", "pre-construction"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "20 min",
    createdAt: "2026-03-08T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "res-equipment",
    title: "Equipment Maintenance & Care",
    description:
      "Well-maintained equipment means reliable service and fewer callbacks. Learn daily, weekly, and monthly maintenance routines for sprayers, backpacks, vehicle rigs, and handheld tools.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-equipment",
    tags: ["equipment", "maintenance"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "12 min",
    createdAt: "2026-03-09T00:00:00Z",
    updatedAt: "2026-03-09T00:00:00Z",
  },
  {
    id: "res-mixing-sds",
    title: "Product Mixing & Safety Data Sheets",
    description:
      "Accurate product mixing protects your health, the customer's property, and Hydra's reputation. Learn proper mixing ratios and how to read Safety Data Sheets.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-equipment",
    tags: ["mixing", "sds", "safety"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "15 min",
    createdAt: "2026-03-10T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "res-upselling",
    title: "Upselling Services the Right Way",
    description:
      "Great technicians solve problems customers didn't know they had — without being pushy. Identify upsell opportunities and present them as genuine value.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-sales",
    tags: ["sales", "upselling"],
    assignedDepartments: ["dept-ops", "dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "10 min",
    createdAt: "2026-03-11T00:00:00Z",
    updatedAt: "2026-03-11T00:00:00Z",
  },
  {
    id: "res-referrals",
    title: "Generating Referrals",
    description:
      "Happy customers are your best marketing channel. Learn how to ask for referrals at the right time and make it easy for customers to spread the word.",
    type: "training",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    categoryId: "cat-sales",
    tags: ["referrals", "growth"],
    assignedDepartments: ["dept-ops", "dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    duration: "8 min",
    createdAt: "2026-03-12T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "res-pest-field-card",
    title: "Pest Identification Field Card",
    description:
      "Printable quick-reference card for field use. Covers the top 20 pests in Arizona with photos, key identifiers, and recommended treatment approach.",
    type: "pdf",
    url: "#",
    categoryId: "cat-pest-id",
    tags: ["field-card", "identification", "reference"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "1.8 MB",
    createdAt: "2026-03-15T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "res-sds-binder",
    title: "Safety Data Sheet Binder",
    description:
      "Complete collection of SDS documents for every product in the Hydra product lineup. Required to be accessible on every service vehicle.",
    type: "pdf",
    url: "#",
    categoryId: "cat-safety",
    tags: ["sds", "safety", "compliance"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: true,
    fileSize: "12.6 MB",
    createdAt: "2026-03-16T00:00:00Z",
    updatedAt: "2026-03-16T00:00:00Z",
  },
  {
    id: "res-service-checklist",
    title: "Service Visit Checklist Template",
    description:
      "Standard checklist for every residential and commercial service visit. Ensures consistency and completeness across all technicians.",
    type: "document",
    url: "#",
    categoryId: "cat-company",
    tags: ["checklist", "service", "template"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "340 KB",
    createdAt: "2026-03-18T00:00:00Z",
    updatedAt: "2026-03-18T00:00:00Z",
  },
  {
    id: "res-az-regulations",
    title: "Arizona Pest Control Regulations",
    description:
      "Link to the Arizona Department of Agriculture Pest Management Division regulations. All technicians must be familiar with state licensing and compliance requirements.",
    type: "link",
    url: "https://agriculture.az.gov/pestspest-control/pest-management-division",
    categoryId: "cat-safety",
    tags: ["regulations", "compliance", "arizona"],
    assignedDepartments: [],
    assignedPositions: [],
    requiredForOnboarding: false,
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "res-pricing-guide",
    title: "Service Pricing & Packages Guide",
    description:
      "Current pricing for all Hydra services, package bundles, and seasonal promotions. Updated monthly. Essential reference for sales conversations.",
    type: "pdf",
    url: "#",
    categoryId: "cat-sales",
    tags: ["pricing", "sales", "packages"],
    assignedDepartments: ["dept-sales"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "2.1 MB",
    createdAt: "2026-03-22T00:00:00Z",
    updatedAt: "2026-03-25T00:00:00Z",
  },
  {
    id: "res-route-optimization",
    title: "Route Optimization Best Practices",
    description:
      "Tips and tools for planning efficient daily routes. Covers GPS tools, stop sequencing, and how to minimize windshield time while maximizing completed jobs.",
    type: "document",
    url: "#",
    categoryId: "cat-company",
    tags: ["routes", "efficiency", "operations"],
    assignedDepartments: ["dept-ops"],
    assignedPositions: [],
    requiredForOnboarding: false,
    fileSize: "520 KB",
    createdAt: "2026-03-25T00:00:00Z",
    updatedAt: "2026-03-25T00:00:00Z",
  },
];

export function getInitialState(): PortalState {
  return {
    employees: [
      {
        id: "emp-001",
        name: "Admin User",
        email: "admin@hydrapest.com",
        pin: "0000",
        role: "admin",
        departmentId: "dept-ops",
        positionId: "pos-gm",
        locationId: "loc-gila",
        status: "active",
        createdAt: "2026-01-01T00:00:00Z",
      },
      {
        id: "emp-002",
        name: "Marcus Rivera",
        email: "marcus@hydrapest.com",
        pin: "1234",
        role: "employee",
        departmentId: "dept-ops",
        positionId: "pos-tech",
        locationId: "loc-gila",
        status: "active",
        createdAt: "2026-02-15T00:00:00Z",
      },
      {
        id: "emp-003",
        name: "Sarah Chen",
        email: "sarah@hydrapest.com",
        pin: "5678",
        role: "manager",
        departmentId: "dept-sales",
        positionId: "pos-sales",
        locationId: "loc-white",
        status: "active",
        createdAt: "2026-02-20T00:00:00Z",
      },
    ],
    departments: [
      { id: "dept-ops", name: "Operations", description: "Field operations and service delivery", color: "hydra-teal" },
      { id: "dept-sales", name: "Sales", description: "Sales and customer acquisition", color: "hydra-cyan" },
      { id: "dept-admin", name: "Administration", description: "Office and administrative support", color: "hydra-gray" },
    ],
    positions: [
      { id: "pos-gm", name: "General Manager", departmentId: "dept-ops" },
      { id: "pos-tech", name: "Technician", departmentId: "dept-ops" },
      { id: "pos-sales", name: "Sales Rep", departmentId: "dept-sales" },
    ],
    locations: [
      { id: "loc-gila", region: "Gila Valley", address: "2158 N Reay Ln Suite 1, Thatcher, AZ 85552", phone: "833-493-7229" },
      { id: "loc-white", region: "White Mountains", address: "1080 N 16th St Suite 300, Show Low, AZ 85901", phone: "833-493-7229" },
      { id: "loc-sierra", region: "Sierra Vista", address: "4148 Industry Dr Suite 1111, Sierra Vista, AZ 85650", phone: "833-493-7229" },
    ],
    resources,
    categories,
    completions: [],
  };
}

export function getAllResourceIds(): string[] {
  return resources.map((r) => r.id);
}
